replicaCount: 1

image:
  repository: paas-agent
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  annotations: {}

rbac:
  create: true

config:
  clusterID: cluster_dev
  controlPlaneURL: http://paas-server.paas-system.svc.cluster.local:8080
  agentNamespaces: argocd,order-dev,order-test
  argocdNamespace: argocd
  heartbeatInterval: 10s
  snapshotInterval: 30s

secret:
  existingSecret: ""
  token: change-me

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
